"""World-mm adapters around the external pinned SINR SIREN and FFD classes."""
from __future__ import annotations

import math

import torch
import torch.nn.functional as F
from torch import nn

from ._upstream import add_upstream_to_path

add_upstream_to_path("SINR")
from networks.networks import BSplineSiren  # noqa: E402
from models.transformation import CubicBSplineFFDTransform  # noqa: E402


def _triple(value: int | tuple[int, int, int]) -> tuple[int, int, int]:
    return (value, value, value) if isinstance(value, int) else tuple(int(x) for x in value)


class SINRFFDBasis(nn.Module):
    """Generate vector MBCs with upstream ``BSplineSiren`` and upstream FFD.

    The upstream FFD is kept in grid units.  This adapter's only numerical
    conversion is explicit grid-unit to patient-world-mm scaling per DVF axis.
    """

    def __init__(self, lower_world_mm: torch.Tensor, upper_world_mm: torch.Tensor, *, grid_shape: tuple[int, int, int], cps: int | tuple[int, int, int], hidden_dim: int = 64) -> None:
        super().__init__()
        self.register_buffer("lower_world_mm", lower_world_mm.to(dtype=torch.float32))
        self.register_buffer("upper_world_mm", upper_world_mm.to(dtype=torch.float32))
        if self.lower_world_mm.shape != (3,) or self.upper_world_mm.shape != (3,) or torch.any(self.upper_world_mm <= self.lower_world_mm):
            raise ValueError("world bounds must be ordered [3] millimetres")
        self.grid_shape, self.cps = _triple(grid_shape), _triple(cps)
        if min(*self.grid_shape, *self.cps, hidden_dim) <= 0:
            raise ValueError("grid_shape, cps, and hidden_dim must be positive")
        self.control_shape = tuple(int(math.ceil(size / stride)) + 2 for size, stride in zip(self.grid_shape, self.cps))
        self.register_buffer("grid_spacing_mm", (self.upper_world_mm - self.lower_world_mm) / torch.tensor([size - 1 for size in self.grid_shape], dtype=torch.float32))
        self.siren = BSplineSiren([3, hidden_dim, hidden_dim, 9])
        self.ffd = CubicBSplineFFDTransform(ndim=3, img_size=self.grid_shape, cps=self.cps)

    def control_parameters_grid_units(self, batch_size: int) -> torch.Tensor:
        axes = [torch.linspace(-1., 1., size, device=self.lower_world_mm.device, dtype=self.lower_world_mm.dtype) for size in self.control_shape]
        coordinates = torch.stack(torch.meshgrid(*axes, indexing="ij"), dim=-1).reshape(-1, 3)
        values = self.siren(coordinates).reshape(*self.control_shape, 9).permute(3, 0, 1, 2).unsqueeze(0)
        return values.expand(batch_size, -1, -1, -1, -1)

    def dense_dvf_mm(self, controls_grid_units: torch.Tensor) -> torch.Tensor:
        if controls_grid_units.ndim != 5 or controls_grid_units.shape[1:] != (9, *self.control_shape):
            raise ValueError("controls must be [B,9,*control_shape] in upstream grid units")
        dense_grid_units = self.ffd(controls_grid_units)
        return (dense_grid_units.reshape(-1, 3, 3, *self.grid_shape) * self.grid_spacing_mm.view(1, 1, 3, 1, 1, 1)).reshape_as(dense_grid_units)

    def forward(self, points_world_mm: torch.Tensor) -> torch.Tensor:
        if points_world_mm.ndim != 3 or points_world_mm.shape[-1] != 3:
            raise ValueError("points_world_mm must be [B,N,3]")
        batch, count = points_world_mm.shape[:2]
        dense = self.dense_dvf_mm(self.control_parameters_grid_units(batch))
        normalized = 2. * (points_world_mm - self.lower_world_mm) / (self.upper_world_mm - self.lower_world_mm) - 1.
        grid = normalized[..., [2, 1, 0]].reshape(batch, count, 1, 1, 3)
        sampled = F.grid_sample(dense, grid, mode="bilinear", padding_mode="zeros", align_corners=True)
        return sampled.reshape(batch, 3, 3, count).permute(0, 3, 1, 2)


class RespiratorySINRMBCAdapter(nn.Module):
    """Three DREME respiratory MBC levels, each generated by source SINR."""
    def __init__(self, lower_world_mm: torch.Tensor, upper_world_mm: torch.Tensor, *, grid_shapes: tuple[tuple[int, int, int], ...] = ((8, 8, 8), (12, 12, 12), (16, 16, 16)), cps: int | tuple[int, int, int] = 2, hidden_dim: int = 64) -> None:
        super().__init__()
        if len(grid_shapes) != 3: raise ValueError("v3 respiratory branch requires exactly three levels")
        self.levels = nn.ModuleList([SINRFFDBasis(lower_world_mm, upper_world_mm, grid_shape=shape, cps=cps, hidden_dim=hidden_dim) for shape in grid_shapes])

    def forward(self, points_world_mm: torch.Tensor) -> torch.Tensor:
        return torch.stack([level(points_world_mm) for level in self.levels], dim=1)


class CardiacSINRMBCAdapter(nn.Module):
    """One local cardiac SINR MBC with an adapter-only smooth box taper."""
    def __init__(self, lower_world_mm: torch.Tensor, upper_world_mm: torch.Tensor, *, grid_shape: tuple[int, int, int] = (16, 16, 16), cps: int | tuple[int, int, int] = 2, hidden_dim: int = 64, taper_mm: float = 4.) -> None:
        super().__init__()
        if taper_mm <= 0: raise ValueError("taper_mm must be positive")
        self.basis = SINRFFDBasis(lower_world_mm, upper_world_mm, grid_shape=grid_shape, cps=cps, hidden_dim=hidden_dim)
        self.register_buffer("lower_world_mm", lower_world_mm.to(dtype=torch.float32)); self.register_buffer("upper_world_mm", upper_world_mm.to(dtype=torch.float32)); self.taper_mm = float(taper_mm)

    def forward(self, points_world_mm: torch.Tensor) -> torch.Tensor:
        field = self.basis(points_world_mm)
        distance = torch.minimum(points_world_mm - self.lower_world_mm, self.upper_world_mm - points_world_mm)
        taper = (distance / self.taper_mm).clamp(0., 1.).amin(dim=-1)
        return field * taper[..., None, None]
