"""功能：以 SINR 生成 control-point displacement、再用 cubic B-spline FFD 查询 mm MBC。
论文来源：S2V-DREME SINR MBC；SINR CubicBSplineFFDTransform semantics。
输入：world-mm query points及显式 mm control grid bounds。
输出：continuous world-mm MBC；respiratory 保持 3 levels，cardiac 保持 1 local level。
主要步骤：control coordinates→sine INR→control displacement→legacy cubic FFD primitive。
是否属于原论文直接实现 / 必要适配 / 可选实验：SINR parameterization direct principle；mm domain/grid metadata is necessary adaptation。
命令行使用示例：由 Phase-2 dynamic forward 导入，无独立 CLI。
"""
from __future__ import annotations
import torch
from torch import nn
from cardioresp4d.models.bspline_mbc import CubicBSplineMBC

class _SineLayer(nn.Module):
    def __init__(self, in_dim:int, out_dim:int, omega:float=20.0): super().__init__(); self.linear=nn.Linear(in_dim,out_dim); self.omega=omega; nn.init.uniform_(self.linear.weight,-1/in_dim,1/in_dim); nn.init.zeros_(self.linear.bias)
    def forward(self,x): return torch.sin(self.omega*self.linear(x))

class SINRMBC(nn.Module):
    """One physical-mm B-spline MBC whose controls are generated by a small SINR."""
    def __init__(self, domain_min_mm:torch.Tensor, domain_max_mm:torch.Tensor, resolution:int, *, cardiac:bool=False, hidden_dim:int=32, paper_reference_spacing:int|None=None, grid_interval_definition:str='control_points_include_cubic_boundary'):
        super().__init__(); self.ffd=CubicBSplineMBC(domain_min_mm,domain_max_mm,resolution,cardiac=cardiac); self.cardiac=cardiac
        self.sinr=nn.Sequential(_SineLayer(3,hidden_dim),_SineLayer(hidden_dim,hidden_dim),nn.Linear(hidden_dim,3)); nn.init.zeros_(self.sinr[-1].weight); nn.init.zeros_(self.sinr[-1].bias)
        self.paper_reference_spacing=paper_reference_spacing; self.grid_interval_definition=grid_interval_definition
        axis=[torch.linspace(float(domain_min_mm[i]),float(domain_max_mm[i]),resolution) for i in range(3)]
        mesh=torch.meshgrid(*axis,indexing='ij'); coords=torch.stack(mesh,-1); self.register_buffer('control_coordinates_mm',coords); self.register_buffer('actual_control_point_spacing_mm',(torch.as_tensor(domain_max_mm)-torch.as_tensor(domain_min_mm))/max(resolution-3,1))
    def control_displacements_mm(self)->torch.Tensor:
        shape=self.control_coordinates_mm.shape[:-1]; normalized=2*(self.control_coordinates_mm-self.ffd.domain_min_mm)/(self.ffd.domain_max_mm-self.ffd.domain_min_mm)-1
        values=self.sinr(normalized.reshape(-1,3)).reshape(*shape,3).permute(3,0,1,2)
        return values*self.ffd.control_mask
    def forward(self,points_mm:torch.Tensor)->torch.Tensor: return self.ffd(points_mm,self.control_displacements_mm())
    def grid_metadata(self)->dict[str,object]: return {'paper_reference_spacing':self.paper_reference_spacing,'grid_interval_definition':self.grid_interval_definition,'actual_control_point_spacing_mm':self.actual_control_point_spacing_mm.detach().cpu().tolist()}

class RespiratorySINRMBC(nn.Module):
    def __init__(self, domain_min_mm:torch.Tensor, domain_max_mm:torch.Tensor, resolutions:tuple[int,int,int]=(8,12,16), paper_reference_spacing:tuple[int,int,int]=(7,5,3)):
        super().__init__(); self.levels=nn.ModuleList([SINRMBC(domain_min_mm,domain_max_mm,r,paper_reference_spacing=s) for r,s in zip(resolutions,paper_reference_spacing)])
    def forward(self,points_mm:torch.Tensor)->torch.Tensor: return torch.stack([level(points_mm) for level in self.levels],dim=-3)

class CardiacSINRMBC(SINRMBC):
    def __init__(self, domain_min_mm:torch.Tensor, domain_max_mm:torch.Tensor,resolution:int=16,paper_reference_spacing:int=3): super().__init__(domain_min_mm,domain_max_mm,resolution,cardiac=True,paper_reference_spacing=paper_reference_spacing)
